# Setup
title:        "CPEN 333: System Software Engineering"
tagline:      "Course material"
baseurl:      ""

# About/contact
author:
  name:       Antonio Sanchez
  url:        

#Others
markdown: kramdown

# Custom
collections:
  lectures:
    output: true
    permalink: /:collection/:path/
